// resources/js/login-link.vue
<script setup>
import { router } from '@inertiajs/vue3';

const props = defineProps({
    label: { type: String, default: () => 'Login' },
    class: { type: String, default: () => 'underline' },
    email: String,
    key: String,
    redirectUrl: String,
    guard: String,
    userAttributes: { type: Object, default: () => null },
})

function submit() {
    router.post(route('loginLinkLogin'), {
        email: props.email,
        key: props.key,
        redirect_url: props.redirectUrl,
        guard: props.guard,
        user_attributes: props.userAttributes,
    })
}
</script>

<template>
    <form @submit.prevent="submit">
        <button :class="props.class" type="submit">
            {{ props.label }}
        </button>
    </form>
</template>

// resources/js/LoginLink.jsx
import React from 'react';
import { router } from '@inertiajs/react'

const LoginLink = ({
    className = 'underline',
    email = null,
    guard = null,
    keyId = null,
    label = 'Login',
    redirectUrl = null,
    userAttributes = null,
}) => {
    const submit = (event) => {
        event.preventDefault();
        router.post(route('loginLinkLogin'), {
            email: email,
            key: keyId,
            redirect_url: redirectUrl,
            guard: guard,
            user_attributes: userAttributes,
        });
    };

    return (
        <form onSubmit={submit}>
            <button className={className} type="submit">
                {label}
            </button>
        </form>
    );
};

export default LoginLink;
