// resources/js/login-link.vue
<script setup>
import { router } from '@inertiajs/vue3';

const props = defineProps({
    label: { type: String, default: () => 'Login' },
    class: { type: String, default: () => 'underline' },
    email: String,
    key: String,
    redirectUrl: String,
    guard: String,
    userAttributes: { type: Object, default: () => null },
})

function submit() {
    router.post(route('loginLinkLogin'), {
        email: props.email,
        key: props.key,
        redirect_url: props.redirectUrl,
        guard: props.guard,
        user_attributes: props.userAttributes,
    })
}
</script>

<template>
    <form @submit.prevent="submit">
        <button :class="props.class" type="submit">
            {{ props.label }}
        </button>
    </form>
</template>

// resources/ts/LoginLink.tsx
import React, { FormEvent } from 'react';
import { router } from '@inertiajs/react'

interface LoginLinkProps {
    className?: string;
    email?: string;
    guard?: string;
    keyId?: string;
    label?: string;
    redirectUrl?: string;
    userAttributes?: Record<string, any>;
}

export default function LoginLink({
    className = 'underline',
    email = null,
    guard = null,
    keyId = null,
    label = 'Login',
    redirectUrl = null,
    userAttributes = null,
}: LoginLinkProps) {
    function submit(event: FormEvent) {
        event.preventDefault();
        router.post(route('loginLinkLogin'), {
            email: email,
            key: keyId,
            redirect_url: redirectUrl,
            guard: guard,
            user_attributes: userAttributes,
        });
    };

    return (
        <form onSubmit={submit}>
            <button className={className} type="submit">
                {label}
            </button>
        </form>
    );
};
